//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqueezeIt.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqueezeIt.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best.
        /// </summary>
        public static string CompressRation_Best {
            get {
                return ResourceManager.GetString("CompressRation_Best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string CompressRation_High {
            get {
                return ResourceManager.GetString("CompressRation_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string CompressRation_Low {
            get {
                return ResourceManager.GetString("CompressRation_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string CompressRation_Medium {
            get {
                return ResourceManager.GetString("CompressRation_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string grdHeader_File {
            get {
                return ResourceManager.GetString("grdHeader_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        public static string grdHeader_FileSize {
            get {
                return ResourceManager.GetString("grdHeader_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string grdHeader_ImgDimensions {
            get {
                return ResourceManager.GetString("grdHeader_ImgDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Dimensions.
        /// </summary>
        public static string grdHeader_NewDimensions {
            get {
                return ResourceManager.GetString("grdHeader_NewDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File Size.
        /// </summary>
        public static string grdHeader_NewFileSize {
            get {
                return ResourceManager.GetString("grdHeader_NewFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduction.
        /// </summary>
        public static string grdHeader_Reduction {
            get {
                return ResourceManager.GetString("grdHeader_Reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string grdHeader_Result {
            get {
                return ResourceManager.GetString("grdHeader_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwritting confirmation.
        /// </summary>
        public static string MessageBox_ConfirmHeader {
            get {
                return ResourceManager.GetString("MessageBox_ConfirmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen to override the original files.\r\nDo you want to continue.
        /// </summary>
        public static string MessageBox_ConfirmOverwrite {
            get {
                return ResourceManager.GetString("MessageBox_ConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width and height will be changed but the proportions of the image (aspect ratio) will be preserved.
        /// </summary>
        public static string ResizeWarning {
            get {
                return ResourceManager.GetString("ResizeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Result_Cancelled {
            get {
                return ResourceManager.GetString("Result_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueued.
        /// </summary>
        public static string Result_Enqueued {
            get {
                return ResourceManager.GetString("Result_Enqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Result_Error {
            get {
                return ResourceManager.GetString("Result_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:  {0}.
        /// </summary>
        public static string Result_ErrorWithException {
            get {
                return ResourceManager.GetString("Result_ErrorWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Result_Ok {
            get {
                return ResourceManager.GetString("Result_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok. New file = {0}.
        /// </summary>
        public static string Result_OkOverwrite {
            get {
                return ResourceManager.GetString("Result_OkOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Result_Processing {
            get {
                return ResourceManager.GetString("Result_Processing", resourceCulture);
            }
        }
    }
}
